spring:
  application:
    name: waymore

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS}

auth:
  cookie:
    refresh-token:
      name: ${REFRESH_TOKEN_COOKIE_NAME}
      path: ${REFRESH_TOKEN_COOKIE_PATH}
      secure: ${REFRESH_TOKEN_COOKIE_SECURE}
      same-site: ${REFRESH_TOKEN_COOKIE_SAME_SITE}
app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000, http://127.0.0.1:3000}
    allowed-origin-patterns: ${APP_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:3000, http://127.0.0.1:3000}